### ISSUE TITLE
org.apache.tomcat.util.http.fileupload.FileUploadBase$FileSizeLimitExceededException

### ISSUE THREAD

**Issue by GenweiWu** [GenweiWu/Blog#40]
# Spring上传文件报文件太大：
```
org.apache.tomcat.util.http.fileupload.FileUploadBase$FileSizeLimitExceededException
```

**Comment by GenweiWu** [comment]
## 解决方法
```yml
spring:
    http:
      multipart:
       max-file-size: 1024MB
       max-request-size: 1024MB
```
