### ISSUE TITLE
设置height:100%页面出现滚动条

### ISSUE THREAD

**Issue by GenweiWu** [GenweiWu/Blog#57]
> html
```html
<!DOCTYPE html>
<html>

  <body>

    <div class="area">
      <div class="inner1">
      </div>
    </div>

  </body>

</html>
```

> css
```css
html,
body {
  height: 100%;
  margin: 0;
}

.area {
  box-sizing: border-box;
  height: 100%;
  background: red;
  /* 块格式化上下文来规避 外边距合并 */
  /* overflow:auto; */
  /* padding-top:1px; */
}

.inner1 {
  height: 200px;
  background: yellow;
  /* (1)子元素的margin会导致滚动条出现 */
  margin-top: 10px;
}
```

出现滚动条
![image](https://user-images.githubusercontent.com/16630659/52625705-892b8100-2eec-11e9-8ef3-3936f8259eb5.png)
