### ISSUE TITLE
微信小程序

### ISSUE THREAD

**Issue by GenweiWu** [GenweiWu/Blog#63]

**Comment by GenweiWu** [comment]
### 后台管理
- 个人中心
https://mp.weixin.qq.com/wxopen/initprofile?action=home&token=1877796054&lang=zh_CN

- 入门
https://developers.weixin.qq.com/miniprogram/introduction/

### github上资料清单
- https://github.com/justjavac/awesome-wechat-weapp
- https://github.com/Tencent/weui-wxss

**Comment by GenweiWu** [comment]
## 地图导航功能
```html
<navigator bindtap='click'>
</navigator>
```

```ts
  click: function() {
    wx.openLocation({
      latitude: 23.362490,
      longitude: 116.715790,
      scale: 18,
      name: '华乾大厦',
      address: '金平区长平路93号'
    })
  }
```

**Comment by GenweiWu** [comment]
```js
// pages/shop-list/shop-list.js
Page({

  /**
   * 页面的初始数据
   */
  data: {
    shopList: [{
        logo: '../../images/keji2.jpg',
        title: "欧凡电子烟111",
        desc: "青岛市北区太懂步打断点行街38号11",
        duration: "10：00~20：00",
        distance: "200KM",
        position: "xx"
      },
      {
        logo: '../../images/jump.gif',
        title: "欧凡电子烟222",
        desc: "青岛市北区太懂步打断点行街38号22",
        duration: "10：00~23：00",
        distance: "400KM",
        position: "xx"
      }
    ]
  },

  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function(options) {

  },

  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady: function() {

  },

  /**
   * 生命周期函数--监听页面显示
   */
  onShow: function() {

  },

  /**
   * 生命周期函数--监听页面隐藏
   */
  onHide: function() {

  },

  /**
   * 生命周期函数--监听页面卸载
   */
  onUnload: function() {

  },

  /**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh: function() {

  },

  /**
   * 页面上拉触底事件的处理函数
   */
  onReachBottom: function() {

  },

  /**
   * 用户点击右上角分享
   */
  onShareAppMessage: function() {

  },

  position: function() {
    wx.openLocation({
      latitude: 23.362490,
      longitude: 116.715790,
      scale: 18,
      name: '华乾大厦',
      address: '金平区长平路93号'
    })
  }
})
```

```html
<!--pages/shop-list/shop-list.wxml-->
<!-- <text>pages/shop-list/shop-list.wxml</text> -->

<scroll-view>

  <navigator class='item' wx:for="{{shopList}}" wx:for-item="shop" bindtap='position'>
    <view>
      <image class='logo' src="{{shop.logo}}"></image>
    </view>
    <view class='desc'>
      <text class='title' style='display:block;'>{{shop.title}}</text>
      <text class='detail'>{{shop.desc}}</text>
      <text class='detail' style='display:block;'>{{shop.duration}}</text>
    </view>
    <view class='route'>
      <view class='distance'>
        <text>{{shop.distance}}</text>
      </view>

    </view>
  </navigator>

  <!-- <navigator class='item'>
    <view>
      <image class='logo' src="../../images/keji2.jpg"></image>
    </view>
    <view class='desc'>
      <text class='title' style='display:block;'>欧凡电子烟</text>
      <text class='detail'>青岛市北区太懂步打断点行街38号</text>
      <text class='detail' style='display:block;'>10：00~20：00</text>
    </view>
    <view class='route'>
      <view class='distance'>
        <text>200KM</text>
      </view>

    </view>
  </navigator> -->


</scroll-view>
```

```css
/* pages/shop-list/shop-list.wxss */

.item {
  padding: 10px;
  overflow: auto;
  display: flex;
  border: 1px solid transparent;
  border-bottom-color: #ebebeb;
  border-top-color: #ebebeb;
}

.logo {
  width: 60px;
  height: 60px;
  border: 4px solid #fff;
  border-radius: 8px;
  margin-right: 5px;
}

.desc {
  overflow: auto;
  margin-left: 5px;
  flex: 1.5;
}

.desc>text {
  display: block;
}

.desc>.title {
  font-size: 15px;
  font-weight: bold;
}

.desc>.detail {
  font-size: 12px;
  margin-top: 5px;
  word-break: break-word;
}

.route {
  margin-left: 5px;
  flex: 1;
}

.distance {
  padding: 3px;
  border: 2px solid #0366d6;
  text-align: center;
  margin: 0 5px;
}

```
