### ISSUE TITLE
父div的高度被子div的padding影响

### ISSUE THREAD

**Issue by GenweiWu** [GenweiWu/Blog#64]

**Comment by GenweiWu** [comment]
```html
  <div class="outer" style="padding-top:0;padding-bottom:0;">
    <div class="inner"></div>
  </div>

  <div class="outer" style="padding-top:16px;padding-bottom:0;">
    <div class="inner"></div>
  </div>
  
  <div class="outer" style="padding-top:0;padding-bottom:16px;">
    <div class="inner"></div>
  </div>
  
  <div class="outer" style="padding-top:16px;padding-bottom:16px;">
    <div class="inner"></div>
  </div>
```

```css
.outer{
  outline:1px solid blue;
  width:20%;
}


.inner{
  height:50px;
  background:orange;
  margin-top:10px;
  margin-bottom:-30px;
}
```

界面不太重要，大概是这样的：
![image](https://user-images.githubusercontent.com/16630659/56889829-2177e180-6aaa-11e9-9e55-94c4c2a9e01f.png)

重点是，四个div的盒模型分别是：
1)
![image](https://user-images.githubusercontent.com/16630659/56889860-41a7a080-6aaa-11e9-91bc-bd6507707e2e.png)

2)
![image](https://user-images.githubusercontent.com/16630659/56889866-49ffdb80-6aaa-11e9-93f5-4fe47c62463a.png)

3)
![image](https://user-images.githubusercontent.com/16630659/56889876-5126e980-6aaa-11e9-9974-64ca4c9d4703.png)

4)
![image](https://user-images.githubusercontent.com/16630659/56889881-57b56100-6aaa-11e9-929a-40491c4ffb65.png)

**Comment by GenweiWu** [comment]
## 我的理解
子元素的`margin`实际上发生了外边距合并，但是`padding`会阻止对应位置的外边距合并，
即父元素的`padding-top`阻止了子元素的`margin-top`发生合并，反而看起来是子元素的`margin-top`生效了；类似的父元素的`padding-bottom`阻止了子元素的`margin-bottom`

**Comment by GenweiWu** [comment]
## 发散问题1
```html
  <div class="area">
  
    <div class="outer">
      <div class="inner"></div> 
    </div>

    <div class="outer">
      <div class="inner-holder"></div> 
    </div>
    
  </div>
```

```css
.outer{
  outline:1px solid blue;
  width:20%;
  padding-top:16px;
  padding-bottom:16px;
}


.inner{
  height:50px;
  background:orange;
  margin-top:10px;
  margin-bottom:-30px;
}

.inner-holder{
  height:50px; 
  visibility:visible;
}
```

你会发现`inner-holder`没法模拟`inner`的位置(场景是我们需要实现一个滚动时，按钮看不见时浮动的效果，需要在按钮浮动时，模拟按钮的高度，否则会导致高度变化触发滚动事件死循环)

### :)output
![image](https://user-images.githubusercontent.com/16630659/56890763-f9d64880-6aac-11e9-89a7-bd3d541cbd51.png)

> 发现直接照抄height为50，会模拟的是`82`而之前是`62`
![height_change](https://user-images.githubusercontent.com/16630659/56890815-238f6f80-6aad-11e9-9d11-22f36fd0cdb4.gif)

### :)修复方法
